"""Create users bind tables

Revision ID: 02493c0b8e56
Revises: 642a87acd987
Create Date: 2025-10-23 19:48:22.579724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02493c0b8e56'
down_revision = '642a87acd987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
