"""Add nome_completo and cro_registro to Usuario

Revision ID: 233f59f84a0b
Revises: d68655282661
Create Date: 2025-10-23 22:09:24.290371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233f59f84a0b'
down_revision = 'd68655282661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
