"""Create default bind tables

Revision ID: 29b124a03002
Revises: ae5d09aa7afc
Create Date: 2025-10-23 19:45:11.310746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b124a03002'
down_revision = 'ae5d09aa7afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
