"""Create users bind tables (take 2)

Revision ID: 4db091019238
Revises: 02493c0b8e56
Create Date: 2025-10-23 19:49:37.355481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db091019238'
down_revision = '02493c0b8e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
