"""Create default bind tables (take 2)

Revision ID: 642a87acd987
Revises: 29b124a03002
Create Date: 2025-10-23 19:47:09.048105

"""
from alembic import op
import sqlalchemy as sa


def _on_default_db() -> bool:
    """Return True when running against the default pacientes.db.

    This avoids applying default-bind DDL to other binds (e.g., users/history).
    """
    try:
        bind = op.get_bind()
        url = str(getattr(bind.engine, "url", ""))
        return "pacientes.db" in url
    except Exception:
        return True  # best effort: default to True when uncertain


# revision identifiers, used by Alembic.
revision = '642a87acd987'
down_revision = '29b124a03002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _on_default_db():
        return
    op.create_table(
        'pacientes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome_completo', sa.String(length=200), nullable=False),
        sa.Column('data_nascimento', sa.Date(), nullable=True),
        sa.Column('cpf', sa.String(length=14), nullable=True),
        sa.Column('telefone', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('cep', sa.String(length=9), nullable=True),
        sa.Column('logradouro', sa.String(length=200), nullable=True),
        sa.Column('numero', sa.String(length=20), nullable=True),
        sa.Column('complemento', sa.String(length=100), nullable=True),
        sa.Column('bairro', sa.String(length=120), nullable=True),
        sa.Column('cidade', sa.String(length=120), nullable=True),
        sa.Column('estado', sa.String(length=2), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cpf'),
    )
    op.create_table(
        'procedimentos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=200), nullable=False),
        sa.Column('valor_padrao', sa.Numeric(10, 2), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'anamneses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('paciente_id', sa.Integer(), nullable=False),
        sa.Column('alergias', sa.Text(), nullable=True),
        sa.Column('medicamentos_uso_continuo', sa.Text(), nullable=True),
        sa.Column('historico_doencas', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'],),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('paciente_id'),
    )
    op.create_table(
        'planos_tratamento',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('paciente_id', sa.Integer(), nullable=False),
        sa.Column('dentista_id', sa.Integer(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'PROPOSTO',
                'APROVADO',
                'CONCLUIDO',
                'CANCELADO',
                name='status_plano_enum',
            ),
            server_default=sa.text("'PROPOSTO'"),
            nullable=False,
        ),
        sa.Column('subtotal', sa.Numeric(10, 2), nullable=False),
        sa.Column(
            'desconto',
            sa.Numeric(10, 2),
            server_default=sa.text('0'),
            nullable=False,
        ),
        sa.Column('valor_total', sa.Numeric(10, 2), nullable=False),
        sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'],),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'itens_plano',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plano_id', sa.Integer(), nullable=False),
        sa.Column('procedimento_id', sa.Integer(), nullable=False),
        sa.Column('valor_cobrado', sa.Numeric(10, 2), nullable=False),
        sa.Column('descricao_dente_face', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['plano_id'], ['planos_tratamento.id'],),
        sa.ForeignKeyConstraint(['procedimento_id'], ['procedimentos.id'],),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'lancamentos_financeiros',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plano_id', sa.Integer(), nullable=False),
        sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
        sa.Column(
            'data_lancamento',
            sa.DateTime(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['plano_id'], ['planos_tratamento.id'],),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _on_default_db():
        return
    op.drop_table('lancamentos_financeiros')
    op.drop_table('itens_plano')
    op.drop_table('planos_tratamento')
    op.drop_table('anamneses')
    op.drop_table('procedimentos')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
