"""add developer log and global setting

Revision ID: 8f5ab18d8435
Revises: timeline_evento_contexto_nullable
Create Date: 2025-10-28 08:31:54.213652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5ab18d8435'
down_revision = 'timeline_evento_contexto_nullable'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamentos_fin_estornado_id'))

    with op.batch_alter_table('odontograma_dente_estado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ode_tooth_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odontograma_dente_estado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ode_tooth_id'), ['tooth_id'], unique=False)

    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamentos_fin_estornado_id'), ['lancamento_estornado_id'], unique=False)

    op.drop_table('global_setting')
    # ### end Alembic commands ###
