"""Create all models (initial + financial)

Revision ID: ae5d09aa7afc
Revises: dcb1d45385cc
Create Date: 2025-10-23 19:42:36.757736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5d09aa7afc'
down_revision = 'dcb1d45385cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
