"""Add timeline_evento table for UX Timeline

Revision ID: b1a2c3d4e5f7
Revises: f57281844e93
Create Date: 2025-10-26 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b1a2c3d4e5f7'
down_revision = 'f57281844e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if 'timeline_evento' not in insp.get_table_names():
        op.create_table(
            'timeline_evento',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('paciente_id', sa.Integer(), nullable=False),
            sa.Column('usuario_id', sa.Integer(), nullable=True),
            sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
            sa.Column('evento_tipo', sa.String(length=50), nullable=False),
            sa.Column('descricao', sa.Text(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing_indexes = [ix['name'] for ix in insp.get_indexes('timeline_evento')]
    if 'ix_timeline_evento_paciente_id' not in existing_indexes:
        op.create_index('ix_timeline_evento_paciente_id', 'timeline_evento', ['paciente_id'], unique=False)
    if 'ix_timeline_evento_usuario_id' not in existing_indexes:
        op.create_index('ix_timeline_evento_usuario_id', 'timeline_evento', ['usuario_id'], unique=False)
    if 'ix_timeline_evento_timestamp' not in existing_indexes:
        op.create_index('ix_timeline_evento_timestamp', 'timeline_evento', ['timestamp'], unique=False)
    if 'ix_timeline_evento_evento_tipo' not in existing_indexes:
        op.create_index('ix_timeline_evento_evento_tipo', 'timeline_evento', ['evento_tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_timeline_evento_evento_tipo', table_name='timeline_evento'
    )
    op.drop_index(
        'ix_timeline_evento_timestamp', table_name='timeline_evento'
    )
    op.drop_index(
        'ix_timeline_evento_usuario_id', table_name='timeline_evento'
    )
    op.drop_index(
        'ix_timeline_evento_paciente_id', table_name='timeline_evento'
    )
    op.drop_table('timeline_evento')
    # ### end Alembic commands ###
