"""Add LogAuditoria model for history db

Revision ID: c81434728872
Revises: a9c6c2463a96
Create Date: 2025-10-23 20:36:26.395681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81434728872'
down_revision = 'a9c6c2463a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
