"""Add created_at to PlanoTratamento

Revision ID: cb912c57c696
Revises: a6898713a161
Create Date: 2025-10-23 21:20:21.861626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb912c57c696'
down_revision = 'a6898713a161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos_tratamento', schema=None) as batch_op:
        # For SQLite, adding NOT NULL requires a server_default to backfill
        batch_op.add_column(
            sa.Column(
                'created_at',
                sa.DateTime(),
                nullable=False,
                server_default=sa.text('CURRENT_TIMESTAMP'),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos_tratamento', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
