"""Add has_red_flags to Anamnese

Revision ID: d68655282661
Revises: f57281844e93
Create Date: 2025-10-23 22:01:24.892988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68655282661'
down_revision = 'f57281844e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anamneses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_red_flags', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anamneses', schema=None) as batch_op:
        batch_op.drop_column('has_red_flags')

    # ### end Alembic commands ###
