"""Add Agendamento model

Revision ID: dc840828265a
Revises: 09d7fb808634
Create Date: 2025-10-23 22:30:51.509590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc840828265a'
down_revision = '09d7fb808634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('dentista_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('MARCADO', 'CONFIRMADO', 'SALA_ESPERA', 'EM_ATENDIMENTO', 'FINALIZADO', 'CANCELADO', name='status_agendamento_enum'), server_default=sa.text("'MARCADO'"), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamentos')
    # ### end Alembic commands ###
