"""Create initial and financial models

Revision ID: dcb1d45385cc
Revises: 4153ebd41382
Create Date: 2025-10-23 19:40:59.319067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb1d45385cc'
down_revision = '4153ebd41382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
